enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'GmsCore support'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Copy video URL' 'Downloads' 'Disable rolling number animations' 'Return YouTube Dislike' 'Change start page' 'Enable tablet layout' 'Alternative thumbnails' 'Announcements' 'Enable debugging' 'GmsCore support'"


 [Music-Extended]
 app-name = "Music Ex"
 patches-source = "inotia00/revanced-patches"
 cli-source = "inotia00/revanced-cli"
 rv-brand = "ReVanced Extended"
 build-mode = "module"
 arch = "arm64-v8a"
 apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

 [YouTube-Extended]
 app-name = "YouTube Ex"
 patches-source = "inotia00/revanced-patches"
 cli-source = "inotia00/revanced-cli"
 rv-brand = "ReVanced Extended"
 build-mode = "module"
 apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
 included-patches = "'Hide shortcuts'"
 excluded-patches = "'Alternative thumbnails' 'Change share sheet' 'Change start page' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom double tap length' 'Disable haptic feedback' 'Disable splash animation' 'Enable debug logging' 'GmsCore support' 'Hook YouTube Music actions' 'Hook download actions' 'Layout switch' 'Miniplayer' 'Return YouTube Dislike' 'Translations for YouTube' 'Visual preferences icons for YouTube'"




